Finish chapter 06 Apollo Client
the-road-to-graphql/the-road-to-graphql-chinese pull request #17
Opened 2019-03-21 01:07 UTC by Sasa33

resolve #8 

校对人员：？

2019-03-25 09:39 UTC, xbini requested changes

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +
> It can be coupled with other libraries/frameworks like Vue and Angular as well...

结合上下文,'比如它也可以与 Vue 和 Angular 等其他库 / 框架结合使用',这里不如直接译成‘比如Vue与Angular等’，符合中文阅读习惯

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +> This application starts by introducing Apollo Client with Apollo Boost. The latter allows you to create a zero-configuration Apollo Client to get started the fastest and most convenient way. This s
> This section focuses on the Apollo Client instead of React for the sake of learning.

译成”本节重点是以Apollo Client为学习目的而不是React。“是否更加贴切

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +接下来，你将使用 GitHub 的 GraphQL API，然后在命令行中输出查询和变更的结果。要做到这一点，你需要有一个 GitHub 网站的个人访问令牌，这个我们在前一章中已经介绍过了。如果你还没有完成，请参照 [GitHub 的说明](https://help.github.com/articles/creating-a-personal-access-token-for-the-comm
> 'token'

不需要翻译吧？

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +你在之前的应用程序中做了相同的操作，仅使用 axios 进行纯 HTTP 请求。你使用 GraphQL API endpoint 为 axios 配置了一次，从而让所有的请求都默认访问这个 URI，并且设置授权头。这里也一样，为所有后续的 GraphQL 请求配置一次客户端就足够了。
> You did the same for the previous application

译为'与你以往的应用程序一致'如何？

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +命令式地让 Apollo Client 将查询发送到 GitHub 的 GraphQL API。由于 Apollo Client 是基于 promise 的，`query()` 方法会返回一个你最终可以 resolve 的 promise。由于应用程序是在在命令行中运行的，把结果输出到控制台就足够了。
> Use the Apollo Client `imperatively` to send the query to GitHub's GraphQL API

’imperatively‘这里表述成'快速'会不会更加准确些，使用Apollo Client快速地将查询请求发送至Github的GraphQL API

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +GraphQL 查询中请求的信息可以在 `data` 对象中找到。`data` 对象包含 `organization` 对象及其 `name` 和 `url` 字段。Apollo Client 会自动请求 GraphQL[元字段](http://graphql.org/learn/queries/#meta-fields) `__typename`。Apollo Client 可以使用元字段作为
>  to allow caching and `optimistic` UI updates

`optimistic`此处译为'乐观的'，结合后文'UI的更新'，不太直观呢

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +在我们之前创建的应用程序中，你已经看到过类似的查询结构，因此本节提供几个练习供你测试所学的 GraphQL 技能。解决这些练习将强化你的 GraphQL 技能，这样你以后可以集中精力将 Apollo Client 连接到你的 React 应用程序，而不会遇到任何障碍。在练习结束后，你可以在此应用程序的 GitHub 代码库中找到所有练习的答案，但你应该先尝试自己完成它们。
> Solving the exercises will fortify your GraphQL skills

通过这些练习能够强化你的GraphQL技能。是否更准确？

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +* 确认你 [上一节的源代码](https://github.com/the-road-to-graphql/node-apollo-boost-github-graphql-api/tree/a5b1ce61a3dae3ead1b9795f5bf6e0d090c5d24f)
> `Confirm `

看到这里，忽然感觉到，原文表达的意思是不是`核对`或者`检查`更加准确些呢？

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +  * 扩展 `repositories` 列表字段来查询按 star 数量排序的代码库的有序列表
> Extend the `repositories` list field by querying an ordered list of repositories which is ordered by the number of stargazers

通过查询一个按照star数量排序的有序代码库列表来扩展`repositories`字段，by前后换一下应该会好一些

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +* 将 repository` 节点 ` 的内容提取为可重用的 GraphQL 片段
> `node`

这里不需要翻译吧？

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +## Apollo Client 和一个 GraphQL 变更
> Apollo Client and `a` GraphQL Mutation

这里是标题，`一个`没有必要直译出来吧?

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +前几节你学习了如何使用 Apollo Client 从 GitHub 的 GraphQL API 查询数据。一旦配置好了 Apollo Client，就可以使用其 `query()` 方法发送带有可选 `variables` 的 GraphQL` 查询 `。正如您所了解的那样，我们不仅可以使用 GraphQL 来读取数据，还可以用变更来写入数据。在本节中，您将定义一个变更来为 GitHub 上的
> As `you` have learned...
> `you` are going to...

`你`

2019-03-25 09:39 UTC, xbini commented on manuscript/06-apollo-client/index-cn.md
> +你已经了解了如何在 Node.js 项目中单独使用 Apollo Client。在本章之前，你已经将 React 与不带 Apollo 的 GraphQL 结合使用。在下一章中，你讲把这两种结合起来。尽情期待你的第一个完整的使用 Apollo Client 和 GraphQL 的 React 客户端应用程序吧。
"你`讲`把这两种结合起来"

中文笔误，应为`将`

2019-03-26 02:42 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +
mark

2019-03-26 02:43 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +> This application starts by introducing Apollo Client with Apollo Boost. The latter allows you to create a zero-configuration Apollo Client to get started the fastest and most convenient way. This s
mark

2019-03-26 02:50 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +你在之前的应用程序中做了相同的操作，仅使用 axios 进行纯 HTTP 请求。你使用 GraphQL API endpoint 为 axios 配置了一次，从而让所有的请求都默认访问这个 URI，并且设置授权头。这里也一样，为所有后续的 GraphQL 请求配置一次客户端就足够了。
TBC

2019-03-26 02:57 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +GraphQL 查询中请求的信息可以在 `data` 对象中找到。`data` 对象包含 `organization` 对象及其 `name` 和 `url` 字段。Apollo Client 会自动请求 GraphQL[元字段](http://graphql.org/learn/queries/#meta-fields) `__typename`。Apollo Client 可以使用元字段作为
大家同意用乐观UI更新

2019-03-26 02:58 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +在我们之前创建的应用程序中，你已经看到过类似的查询结构，因此本节提供几个练习供你测试所学的 GraphQL 技能。解决这些练习将强化你的 GraphQL 技能，这样你以后可以集中精力将 Apollo Client 连接到你的 React 应用程序，而不会遇到任何障碍。在练习结束后，你可以在此应用程序的 GitHub 代码库中找到所有练习的答案，但你应该先尝试自己完成它们。
mark

2019-03-26 03:00 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +* 确认你 [上一节的源代码](https://github.com/the-road-to-graphql/node-apollo-boost-github-graphql-api/tree/a5b1ce61a3dae3ead1b9795f5bf6e0d090c5d24f)
看看其它章节怎么翻译的

2019-03-26 03:01 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +  * 扩展 `repositories` 列表字段来查询按 star 数量排序的代码库的有序列表
Mark

2019-03-26 03:02 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +* 将 repository` 节点 ` 的内容提取为可重用的 GraphQL 片段
Mark

2019-03-26 03:02 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +## Apollo Client 和一个 GraphQL 变更
Mark

2019-03-26 03:03 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +前几节你学习了如何使用 Apollo Client 从 GitHub 的 GraphQL API 查询数据。一旦配置好了 Apollo Client，就可以使用其 `query()` 方法发送带有可选 `variables` 的 GraphQL` 查询 `。正如您所了解的那样，我们不仅可以使用 GraphQL 来读取数据，还可以用变更来写入数据。在本节中，您将定义一个变更来为 GitHub 上的
Mark

2019-03-26 03:03 UTC, Sasa33 commented on manuscript/06-apollo-client/index-cn.md
> +你已经了解了如何在 Node.js 项目中单独使用 Apollo Client。在本章之前，你已经将 React 与不带 Apollo 的 GraphQL 结合使用。在下一章中，你讲把这两种结合起来。尽情期待你的第一个完整的使用 Apollo Client 和 GraphQL 的 React 客户端应用程序吧。
Mark

2019-04-09 15:28 UTC, xbini approved these changes
这个校对很早就完成了，一直忘记了approve，sorry！

2019-04-30 02:38 UTC, merged